# Generated by Django 4.2.6 on 2023-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="path_to_file",
            field=models.FilePathField(),
        ),
    ]
