# Generated by Django 4.2.6 on 2023-10-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_alter_photo_path_to_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="path_to_file",
            field=models.FileField(upload_to=""),
        ),
    ]
