# Generated by Django 5.0.4 on 2024-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0005_alter_photo_image_team_userphoto_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userphoto",
            name="segmented_photo",
        ),
        migrations.RemoveField(
            model_name="userphoto",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="userphoto",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="UserPhoto",
        ),
    ]
