# Generated by Django 5.0.4 on 2024-05-05 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0006_uploadedfile_remove_userphoto_segmented_photo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentedPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="segmented/")),
            ],
        ),
        migrations.CreateModel(
            name="UserPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_visible_to_team", models.BooleanField(default=False)),
                (
                    "segmented_photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.segmentedphoto",
                    ),
                ),
                (
                    "uploaded_photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.uploadedfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
