# Generated by Django 5.0.4 on 2024-05-07 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0007_segmentedphoto_userphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_datetime", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.userphoto",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userphoto",
            name="uploaded_photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="myapi.uploadedphoto"
            ),
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
