# Generated by Django 5.0.4 on 2024-05-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0008_uploadedphoto_comment_alter_userphoto_uploaded_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedphoto",
            old_name="file",
            new_name="photo",
        ),
    ]
