# Generated by Django 5.0.4 on 2024-05-12 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0009_rename_file_uploadedphoto_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_photo_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segmented_photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.segmentedphoto",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_photo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.uploadedphoto",
                    ),
                ),
            ],
        ),
    ]
