# Generated by Django 5.0.4 on 2024-05-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0010_teamphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamphoto",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_photo",
                to="myapi.team",
            ),
        ),
    ]
