# Generated by Django 5.0.4 on 2024-05-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0011_alter_teamphoto_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user_photo",
        ),
        migrations.AddField(
            model_name="comment",
            name="team_photo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapi.teamphoto",
            ),
        ),
    ]
