# Generated by Django 5.0.4 on 2024-05-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0012_remove_comment_user_photo_comment_team_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamphoto",
            name="segmented_photo",
        ),
        migrations.RemoveField(
            model_name="teamphoto",
            name="uploaded_photo",
        ),
        migrations.AddField(
            model_name="teamphoto",
            name="user_photo",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapi.userphoto",
            ),
        ),
    ]
